### PR TITLE
Added Wandbox links to README.md

### PR DESCRIPTION
**Pull request by mmha**

### CODE REVIEW

**Review by JeffGarland — APPROVED** [review]

**Comment by JeffGarland** [comment]
thx!

**Comment by JeffGarland** [comment]
Quick question — how is this done — by somehow uploading the text to wandbox to create the link?  I presume we’d need to re-upload if we change the example?

Thx,

Jeff

**Comment by mmha** [comment]
Yes.

You need to paste the source code into Wandbox  and run it. Then, a "Share the Code" button appears right above the Terminal. I don't know if its possible to use e. g. Travis to create a Wandbox link.

**Comment by JeffGarland** [comment]
How did you git Wandbox to include range-v3?

**Comment by mmha** [comment]
Since my answer did not show up on GitHub for some reason, I will write it down again so everyone can read it:

Wandbox distributes range-v3 by default. There is nothing to do to compile a program which uses that library.

**Pull request merged**
